name: calories
description: Calories Tracking
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  numberpicker: ^1.2.0
  bottom_navy_bar: ^5.4.0
  shared_preferences: ^0.5.7+2
  introduction_screen: ^1.0.7
  sqflite:
  path_provider:
  gender_selection: "^0.0.8"






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/Manrope-Regular.ttf
